init_cmd: |
  source setup.sh
windows:
  - name: roscore
    panes:
      - roscore
  - name: mongodb
    panes:
      - roslaunch mongodb_store mongodb_store.launch db_path:=$MONGO_FOLDER machine:=localhost
  - name: simulation
    panes:
      - roslaunch strands_morse ${MAP}_morse.launch env:=${MAP}_fast # NOTE remove `_fast` if you want the fully detailed simulation
  - name: navigation
    panes:
      - roslaunch strands_movebase movebase.launch map:=$MAP_PATH
  - name: create_topological_map
    panes:
      - roslaunch topological_navigation topological_navigation_empty_map.launch map:=$TMAP
      - rviz
  - name: topological_navigation
    panes:
      - roslaunch topological_navigation topological_navigation.launch map:=$TMAP
  - name: plan
    panes:
      - roslaunch pnp_ros pnp_ros.launch
